<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN_1" Id="{436d51fb-b8cc-43d1-95f5-f2c51dd53cc6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>